name: Main tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    container: clojure:openjdk-17-lein-buster
    steps:
      - uses: actions/checkout@v3
      - run: apt update
      - run: apt install -y rake
      - run: lein test :gha
